/*
 * This file is generated by jOOQ.
 */
package com.example.jooqcsv.db.public_;


import com.example.jooqcsv.db.public_.tables.Author;
import com.example.jooqcsv.db.public_.tables.AuthorBook;
import com.example.jooqcsv.db.public_.tables.Book;
import com.example.jooqcsv.db.public_.tables.records.AuthorBookRecord;
import com.example.jooqcsv.db.public_.tables.records.AuthorRecord;
import com.example.jooqcsv.db.public_.tables.records.BookRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<AuthorBookRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
    public static final UniqueKey<BookRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthorBookRecord, AuthorRecord> FK_AB_AUTHOR = ForeignKeys0.FK_AB_AUTHOR;
    public static final ForeignKey<AuthorBookRecord, BookRecord> FK_AB_BOOK = ForeignKeys0.FK_AB_BOOK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorRecord> CONSTRAINT_7 = Internal.createUniqueKey(Author.AUTHOR, "CONSTRAINT_7", new TableField[] { Author.AUTHOR.ID }, true);
        public static final UniqueKey<AuthorBookRecord> CONSTRAINT_A = Internal.createUniqueKey(AuthorBook.AUTHOR_BOOK, "CONSTRAINT_A", new TableField[] { AuthorBook.AUTHOR_BOOK.AUTHOR_ID, AuthorBook.AUTHOR_BOOK.BOOK_ID }, true);
        public static final UniqueKey<BookRecord> CONSTRAINT_1 = Internal.createUniqueKey(Book.BOOK, "CONSTRAINT_1", new TableField[] { Book.BOOK.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AuthorBookRecord, AuthorRecord> FK_AB_AUTHOR = Internal.createForeignKey(Keys.CONSTRAINT_7, AuthorBook.AUTHOR_BOOK, "FK_AB_AUTHOR", new TableField[] { AuthorBook.AUTHOR_BOOK.AUTHOR_ID }, true);
        public static final ForeignKey<AuthorBookRecord, BookRecord> FK_AB_BOOK = Internal.createForeignKey(Keys.CONSTRAINT_1, AuthorBook.AUTHOR_BOOK, "FK_AB_BOOK", new TableField[] { AuthorBook.AUTHOR_BOOK.BOOK_ID }, true);
    }
}
